name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
    
      - name: 'Upload Artifact'
      - uses: actions/upload-artifact@v2 
        with:
          name: production_artifact
          path: ./target/release/ConstantReplacer
          retention-days: 5
